server:
  port: 8082

#logging:
#  level:
#    org:
#      springframework: DEBUG


rocketmq:
  namesrvAddr: 10.60.48.183:9876
  producer:
    groupName: ProducerGroup
    instanceName: ProducerGroup
    topic: test-topic
    tag: test
    maxMessageSize: 131072
    sendMsgTimeout: 10000
  consumer:
    groupName: ConsumerGroup
    topic: test-topic
    tag: test
    consumeThreadMin: 10
    consumeThreadMax: 30
