server:
  port: 10087

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        port: 9002
        dashboard: localhost:8089
      filter:
        url-patterns: /** # 拦截请求的地址。默认为 /*